### ISSUE TITLE
Choose a license for the materials of this repository

### ISSUE THREAD

**Issue by aborruso** [spaghetti-open-data/scriptorivm#5]
My proposal is CC BY 4.0

**Comment by ggattiglia** [comment]
Condivido

2015-03-12 15:09 GMT+01:00 Andrea Borruso notifications@github.com:

**Comment by albertocottica** [comment]
Agree.

**Comment by aborruso** [comment]
Added https://github.com/spaghetti-open-data/scriptorivm
